pmtiles:
  allow_http: true
  access_key_id: "admin"
  secret_access_key: "supersecretpassword"
  region: "us-east-1"
  endpoint_url: "http://minio:9000"
  sources:
    my-forestmap: "s3://maps-bucket/khabarovsk.pmtiles"
